/* $Id$ */
/*
 * Copyright (C) 2012-2013 DigiOn,Inc. (www.digion.com)
 */

#ifndef __RATUN_STATUS_CODE_H__
#define __RATUN_STATUS_CODE_H__

/**
 * @file ratun_status_code.h
 * @brief remote access tunnel status code.
 */

#ifdef __cplusplus
extern "C" {
#endif

typedef enum ratun_status_code
{
    RATUN_SC_TRYING = 100,
    RATUN_SC_RINGING = 180,
    RATUN_SC_CALL_BEING_FORWARDED = 181,
    RATUN_SC_QUEUED = 182,
    RATUN_SC_PROGRESS = 183,

    RATUN_SC_OK = 200,
    RATUN_SC_ACCEPTED = 202,

    RATUN_SC_MULTIPLE_CHOICES = 300,
    RATUN_SC_MOVED_PERMANENTLY = 301,
    RATUN_SC_MOVED_TEMPORARILY = 302,
    RATUN_SC_USE_PROXY = 305,
    RATUN_SC_ALTERNATIVE_SERVICE = 380,

    RATUN_SC_BAD_REQUEST = 400,
    RATUN_SC_UNAUTHORIZED = 401,
    RATUN_SC_PAYMENT_REQUIRED = 402,
    RATUN_SC_FORBIDDEN = 403,
    RATUN_SC_NOT_FOUND = 404,
    RATUN_SC_METHOD_NOT_ALLOWED = 405,
    RATUN_SC_NOT_ACCEPTABLE = 406,
    RATUN_SC_PROXY_AUTHENTICATION_REQUIRED = 407,
    RATUN_SC_REQUEST_TIMEOUT = 408,
    RATUN_SC_GONE = 410,
    RATUN_SC_REQUEST_ENTITY_TOO_LARGE = 413,
    RATUN_SC_REQUEST_URI_TOO_LONG = 414,
    RATUN_SC_UNSUPPORTED_MEDIA_TYPE = 415,
    RATUN_SC_UNSUPPORTED_URI_SCHEME = 416,
    RATUN_SC_BAD_EXTENSION = 420,
    RATUN_SC_EXTENSION_REQUIRED = 421,
    RATUN_SC_SESSION_TIMER_TOO_SMALL = 422,
    RATUN_SC_INTERVAL_TOO_BRIEF = 423,
    RATUN_SC_TEMPORARILY_UNAVAILABLE = 480,
    RATUN_SC_CALL_TSX_DOES_NOT_EXIST = 481,
    RATUN_SC_LOOP_DETECTED = 482,
    RATUN_SC_TOO_MANY_HOPS = 483,
    RATUN_SC_ADDRESS_INCOMPLETE = 484,
    RATUN_SC_AMBIGUOUS = 485,
    RATUN_SC_BUSY_HERE = 486,
    RATUN_SC_REQUEST_TERMINATED = 487,
    RATUN_SC_NOT_ACCEPTABLE_HERE = 488,
    RATUN_SC_BAD_EVENT = 489,
    RATUN_SC_REQUEST_UPDATED = 490,
    RATUN_SC_REQUEST_PENDING = 491,
    RATUN_SC_UNDECIPHERABLE = 493,

    RATUN_SC_INTERNAL_SERVER_ERROR = 500,
    RATUN_SC_NOT_IMPLEMENTED = 501,
    RATUN_SC_BAD_GATEWAY = 502,
    RATUN_SC_SERVICE_UNAVAILABLE = 503,
    RATUN_SC_SERVER_TIMEOUT = 504,
    RATUN_SC_VERSION_NOT_SUPPORTED = 505,
    RATUN_SC_MESSAGE_TOO_LARGE = 513,
    RATUN_SC_PRECONDITION_FAILURE = 580,

    RATUN_SC_BUSY_EVERYWHERE = 600,
    RATUN_SC_DECLINE = 603,
    RATUN_SC_DOES_NOT_EXIST_ANYWHERE = 604,
    RATUN_SC_NOT_ACCEPTABLE_ANYWHERE = 606,

    RATUN_SC_TSX_TIMEOUT = RATUN_SC_REQUEST_TIMEOUT,
    /*RATUN_SC_TSX_RESOLVE_ERROR = 702,*/
    RATUN_SC_TSX_TRANSPORT_ERROR = RATUN_SC_SERVICE_UNAVAILABLE,

    /* This is not an actual status code, but rather a constant
     * to force GCC to use 32bit to represent this enum, since
     * we have a code in RASUA-LIB that assigns an integer
     * to this enum (see rasua_acc_get_info() function).
     */
    RATUN_SC__force_32bit = 0x7FFFFFFF

} ratun_status_code;


#ifdef __cplusplus
}
#endif

#endif /* __RATUN_H__ */
