/*
 * Copyright (c) 2012 DigiOn, Inc. All rights reserved.
 *
 * $Id$
 */
/**
 * @file ratun_manager_error.h
 * @brief error code occurs on ratun manager.
 */
#ifndef RATUN_MANAGER_ERROR_H
#define RATUN_MANAGER_ERROR_H

#include <du_type.h>
#include <ratun_status_code.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef du_uint32 ratun_manager_error_code;

enum {
    RATUN_MANAGER_ERROR_CODE_OK = 0,

    RATUN_MANAGER_ERROR_CODE_INTERNAL = 1200,
    RATUN_MANAGER_ERROR_CODE_NOT_INITIALIZED = 1201,

    RATUN_MANAGER_ERROR_CODE_NETTYPE_UNKNOWN = 1501,
    RATUN_MANAGER_ERROR_CODE_NETTYPE_BLOCKED = 1502,
    RATUN_MANAGER_ERROR_CODE_NETTYPE_SYMMETRIC = 1503,

    /** service authentication errors */
    /** 0x1001 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_HWID = 2000,
    /** 0x1002 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_SID,
    /** 0x1003 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_CRED,
    /** 0x1004 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_SIGN,
    /** 0x1005 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_CERT_A,
    /** 0x1006 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_CERT_A_VER,
    /** 0x1007 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_CERT_D,
    /** 0x1008 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_TICKET,
    /** 0x1009 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_CERT_SIP_SERVER,
    /** 0x10ff */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INVALID_REQUEST,
    /** 0x1101 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_VENDOR,
    /** 0x1102 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_PRODUCT,
    /** 0x1103 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_DEVICE,
    /** 0x1104 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_CERT,
    /** 0x1105 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_SERVICE_P,
    /** 0x1106 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_SERVICE_D,
    /** 0x1107 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_SERVICE_ID,
    /** 0x1108 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_SERVICE_CERT_D,
    /** 0x1109 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_PROHIBITED_SERVICE_CERT_ID,
    /** 0x1201 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_EXCEEDED_CERT_D,
    /** 0x1202 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_EXCEEDED_TICKET_1,
    /** 0x1203 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_EXCEEDED_TICKET_2,
    /** 0x1301 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_REGET_TICKET,
    /** 0x1302 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_REGET_CREDENTIAL,
    /** 0x1303 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INSTRUCT_REG_PROC,
    /** 0x1304 */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR_INSTRUCT_UPD_PROC,
    /** 0xffff */RATUN_MANAGER_ERROR_CODE_AUTH_ERROR,
};

#ifdef __cplusplus
}
#endif

#endif
