/*
 * Copyright (c) 2005 DigiOn, Inc. All rights reserved.
 */

#ifndef DCU_SUBDETECTOR_H
#define DCU_SUBDETECTOR_H

#include "du_type.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DCU_SUBDETECTOR_ID_UTF8 DU_UCHAR_CONST("UTF-8")
#define DCU_SUBDETECTOR_ID_UTF16 DU_UCHAR_CONST("UTF-16")
#define DCU_SUBDETECTOR_ID_UTF16LE DU_UCHAR_CONST("UTF-16LE")
#define DCU_SUBDETECTOR_ID_UTF16BE DU_UCHAR_CONST("UTF-16BE")
#define DCU_SUBDETECTOR_ID_UCS4 DU_UCHAR_CONST("UCS-4")
#define DCU_SUBDETECTOR_ID_UCS4LE DU_UCHAR_CONST("UCS-4LE")
#define DCU_SUBDETECTOR_ID_UCS4BE DU_UCHAR_CONST("UCS-4BE")
#define DCU_SUBDETECTOR_ID_UCS2 DU_UCHAR_CONST("UCS-2")
#define DCU_SUBDETECTOR_ID_UCS2LE DU_UCHAR_CONST("UCS-2LE")
#define DCU_SUBDETECTOR_ID_UCS2BE DU_UCHAR_CONST("UCS-2BE")
#define DCU_SUBDETECTOR_ID_8859_1 DU_UCHAR_CONST("ISO-8859-1")
#define DCU_SUBDETECTOR_ID_8859_2 DU_UCHAR_CONST("ISO-8859-2")
#define DCU_SUBDETECTOR_ID_8859_3 DU_UCHAR_CONST("ISO-8859-3")
#define DCU_SUBDETECTOR_ID_8859_4 DU_UCHAR_CONST("ISO-8859-4")
#define DCU_SUBDETECTOR_ID_8859_5 DU_UCHAR_CONST("ISO-8859-5")
#define DCU_SUBDETECTOR_ID_8859_6 DU_UCHAR_CONST("ISO-8859-6")
#define DCU_SUBDETECTOR_ID_8859_7 DU_UCHAR_CONST("ISO-8859-7")
#define DCU_SUBDETECTOR_ID_8859_8 DU_UCHAR_CONST("ISO-8859-8")
#define DCU_SUBDETECTOR_ID_8859_9 DU_UCHAR_CONST("ISO-8859-9")
#define DCU_SUBDETECTOR_ID_ISO2022JP DU_UCHAR_CONST("ISO-2022-JP")
#define DCU_SUBDETECTOR_ID_SHIFTJIS DU_UCHAR_CONST("Shift_JIS")
#define DCU_SUBDETECTOR_ID_EUCJP DU_UCHAR_CONST("EUC-JP")
#define DCU_SUBDETECTOR_ID_ASCII DU_UCHAR_CONST("ASCII")
#define DCU_SUBDETECTOR_ID_CP932 DU_UCHAR_CONST("CP932")

// default_lang: null, "ja"
// detect DCU_SUBDETECTOR_ID_ISO2022JP, DCU_SUBDETECTOR_ID_SHIFTJIS, DCU_SUBDETECTOR_ID_EUCJP, DCU_SUBDETECTOR_ID_ASCII
extern const du_uchar* dcu_subdetector_detect(const du_uchar* str, du_uint32 len);

extern du_uint32 dcu_subdetector_get_terminate_code_size(const du_uchar* encoding);

extern const du_uchar** dcu_subdetector_get_alias(const du_uchar* encoding);

#ifdef __cplusplus
}
#endif

#endif
